/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { BaseContract, BigNumber, Signer, utils } from "ethers";
import { EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IDeferredTokenEventInterface extends utils.Interface {
  functions: {};

  events: {
    "Deposit(address,uint256)": EventFragment;
    "RequestWithdrawal(address,uint256,uint256)": EventFragment;
    "UpdateCooldownPeriod(uint256)": EventFragment;
    "Withdraw(address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Deposit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RequestWithdrawal"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdateCooldownPeriod"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Withdraw"): EventFragment;
}

export type DepositEvent = TypedEvent<
  [string, BigNumber],
  { owner: string; amount: BigNumber }
>;

export type DepositEventFilter = TypedEventFilter<DepositEvent>;

export type RequestWithdrawalEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  { owner: string; amount: BigNumber; requestId: BigNumber }
>;

export type RequestWithdrawalEventFilter =
  TypedEventFilter<RequestWithdrawalEvent>;

export type UpdateCooldownPeriodEvent = TypedEvent<
  [BigNumber],
  { period: BigNumber }
>;

export type UpdateCooldownPeriodEventFilter =
  TypedEventFilter<UpdateCooldownPeriodEvent>;

export type WithdrawEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  { owner: string; amount: BigNumber; requestId: BigNumber }
>;

export type WithdrawEventFilter = TypedEventFilter<WithdrawEvent>;

export interface IDeferredTokenEvent extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IDeferredTokenEventInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "Deposit(address,uint256)"(
      owner?: string | null,
      amount?: null
    ): DepositEventFilter;
    Deposit(owner?: string | null, amount?: null): DepositEventFilter;

    "RequestWithdrawal(address,uint256,uint256)"(
      owner?: string | null,
      amount?: null,
      requestId?: null
    ): RequestWithdrawalEventFilter;
    RequestWithdrawal(
      owner?: string | null,
      amount?: null,
      requestId?: null
    ): RequestWithdrawalEventFilter;

    "UpdateCooldownPeriod(uint256)"(
      period?: null
    ): UpdateCooldownPeriodEventFilter;
    UpdateCooldownPeriod(period?: null): UpdateCooldownPeriodEventFilter;

    "Withdraw(address,uint256,uint256)"(
      owner?: string | null,
      amount?: null,
      requestId?: null
    ): WithdrawEventFilter;
    Withdraw(
      owner?: string | null,
      amount?: null,
      requestId?: null
    ): WithdrawEventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
