/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export type WithdrawalRequestStruct = {
  id: BigNumberish;
  amount: BigNumberish;
  requestTs: BigNumberish;
  isClaimed: boolean;
};

export type WithdrawalRequestStructOutput = [
  BigNumber,
  BigNumber,
  BigNumber,
  boolean
] & {
  id: BigNumber;
  amount: BigNumber;
  requestTs: BigNumber;
  isClaimed: boolean;
};

export interface IDeferredTokenInterface extends utils.Interface {
  functions: {
    "cooldownPeriod()": FunctionFragment;
    "deposit(uint256)": FunctionFragment;
    "pause()": FunctionFragment;
    "requestWithdrawal(uint256)": FunctionFragment;
    "setCooldownPeriod(uint256)": FunctionFragment;
    "token()": FunctionFragment;
    "unpause()": FunctionFragment;
    "withdraw(uint256)": FunctionFragment;
    "withdrawalRequestByIndex(address,uint256)": FunctionFragment;
    "withdrawalRequestCounts(address)": FunctionFragment;
    "withdrawalRequests(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "cooldownPeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "requestWithdrawal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setCooldownPeriod",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawalRequestByIndex",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawalRequestCounts",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawalRequests",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "cooldownPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCooldownPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawalRequestByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawalRequestCounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawalRequests",
    data: BytesLike
  ): Result;

  events: {
    "Deposit(address,uint256)": EventFragment;
    "RequestWithdrawal(address,uint256,uint256)": EventFragment;
    "UpdateCooldownPeriod(uint256)": EventFragment;
    "Withdraw(address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Deposit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RequestWithdrawal"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdateCooldownPeriod"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Withdraw"): EventFragment;
}

export type DepositEvent = TypedEvent<
  [string, BigNumber],
  { owner: string; amount: BigNumber }
>;

export type DepositEventFilter = TypedEventFilter<DepositEvent>;

export type RequestWithdrawalEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  { owner: string; amount: BigNumber; requestId: BigNumber }
>;

export type RequestWithdrawalEventFilter =
  TypedEventFilter<RequestWithdrawalEvent>;

export type UpdateCooldownPeriodEvent = TypedEvent<
  [BigNumber],
  { period: BigNumber }
>;

export type UpdateCooldownPeriodEventFilter =
  TypedEventFilter<UpdateCooldownPeriodEvent>;

export type WithdrawEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  { owner: string; amount: BigNumber; requestId: BigNumber }
>;

export type WithdrawEventFilter = TypedEventFilter<WithdrawEvent>;

export interface IDeferredToken extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IDeferredTokenInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    cooldownPeriod(overrides?: CallOverrides): Promise<[BigNumber]>;

    deposit(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    requestWithdrawal(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setCooldownPeriod(
      period: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    token(overrides?: CallOverrides): Promise<[string]>;

    unpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdraw(
      requestId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawalRequestByIndex(
      owner: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[WithdrawalRequestStructOutput]>;

    withdrawalRequestCounts(
      owner: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    withdrawalRequests(
      requestId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[WithdrawalRequestStructOutput]>;
  };

  cooldownPeriod(overrides?: CallOverrides): Promise<BigNumber>;

  deposit(
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  pause(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  requestWithdrawal(
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setCooldownPeriod(
    period: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  token(overrides?: CallOverrides): Promise<string>;

  unpause(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdraw(
    requestId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawalRequestByIndex(
    owner: string,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<WithdrawalRequestStructOutput>;

  withdrawalRequestCounts(
    owner: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  withdrawalRequests(
    requestId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<WithdrawalRequestStructOutput>;

  callStatic: {
    cooldownPeriod(overrides?: CallOverrides): Promise<BigNumber>;

    deposit(amount: BigNumberish, overrides?: CallOverrides): Promise<void>;

    pause(overrides?: CallOverrides): Promise<void>;

    requestWithdrawal(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setCooldownPeriod(
      period: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    token(overrides?: CallOverrides): Promise<string>;

    unpause(overrides?: CallOverrides): Promise<void>;

    withdraw(
      requestId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawalRequestByIndex(
      owner: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<WithdrawalRequestStructOutput>;

    withdrawalRequestCounts(
      owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawalRequests(
      requestId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<WithdrawalRequestStructOutput>;
  };

  filters: {
    "Deposit(address,uint256)"(
      owner?: string | null,
      amount?: null
    ): DepositEventFilter;
    Deposit(owner?: string | null, amount?: null): DepositEventFilter;

    "RequestWithdrawal(address,uint256,uint256)"(
      owner?: string | null,
      amount?: null,
      requestId?: null
    ): RequestWithdrawalEventFilter;
    RequestWithdrawal(
      owner?: string | null,
      amount?: null,
      requestId?: null
    ): RequestWithdrawalEventFilter;

    "UpdateCooldownPeriod(uint256)"(
      period?: null
    ): UpdateCooldownPeriodEventFilter;
    UpdateCooldownPeriod(period?: null): UpdateCooldownPeriodEventFilter;

    "Withdraw(address,uint256,uint256)"(
      owner?: string | null,
      amount?: null,
      requestId?: null
    ): WithdrawEventFilter;
    Withdraw(
      owner?: string | null,
      amount?: null,
      requestId?: null
    ): WithdrawEventFilter;
  };

  estimateGas: {
    cooldownPeriod(overrides?: CallOverrides): Promise<BigNumber>;

    deposit(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    requestWithdrawal(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setCooldownPeriod(
      period: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    token(overrides?: CallOverrides): Promise<BigNumber>;

    unpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdraw(
      requestId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawalRequestByIndex(
      owner: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawalRequestCounts(
      owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawalRequests(
      requestId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    cooldownPeriod(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    deposit(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    requestWithdrawal(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setCooldownPeriod(
      period: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    token(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    unpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdraw(
      requestId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawalRequestByIndex(
      owner: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdrawalRequestCounts(
      owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdrawalRequests(
      requestId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
